### PR TITLE
Added two new crosswalks for the Associated Press abbreviations of US. states

### PR DESCRIPTION
**Pull request by palewire**
For #3.

One accepts FIPS codes as an input. The other accepts a USPS postal code.

Not sure I managed how to crosswalk it with two different types of codes, but here's a stab.

### CODE REVIEW

**Comment by palewire** [comment]
Gosh. Now that I think about it. Should it instead crosswalk with full state names like "Alabama?"

**Comment by onyxfish** [comment]
I think this looks great. The only thing to change is that the FIPS codes need to be 0 prefixed, for the reasons described in #6. In checking, I realize I did this wrong in the mapping I created as well. :/

**Comment by palewire** [comment]
I think I just did it.

**Comment by onyxfish** [comment]
Thanks!

**Comment by palewire** [comment]
Would you want one with the full state names connected to the abbreviations
as well?

**Comment by onyxfish** [comment]
Just took a closer look at this. Did you intend for this to map _to_ AP codes or _from_ AP codes?

**Comment by onyxfish** [comment]
Would def like to have one for full state names. The more the merrier.

**Comment by palewire** [comment]
I'm hoping to map to AP names. So I could pass in a FIPS or postal code and get back the AP name.

**Comment by onyxfish** [comment]
Got it, that's what I thought. I shuffled the files around so the hierarchy should work for that.

**Comment by palewire** [comment]
Thank you. Where ought a map that connects full state names to AP abbreviations go?

**Comment by onyxfish** [comment]
So that's an interesting question. I've been on the fence on including state names like, "New York" as a _key_. They make a great value, but I've seen "District of Columbia" a lot of different ways in datasets, so I worry about things not getting joined and that not being obvious.

That being said, having the state name as a key is so obviously useful, I also really want it. If you want to work up a pull request I'll merge it. Let's just be very clear where the state names are from. Census Bureau would probably be ideal.

**Pull request merged**
